config/routes.rb
Hacksgiving2012::Application.routes.draw do
  
  devise_for :admins
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'
  

  devise_for :users

  match 'twiml/voice' => 'twiml#voice'
  match 'twiml/volunteer_voice' => 'twiml#volunteer_voice'
  match 'twiml/sms' => 'twiml#sms'
  match 'twiml/volunteer' => 'twiml#volunteer'
  match 'twiml/voicemail' => 'twiml#voicemail'
  match 'twiml/subscribe' => 'twiml#subscribe'
  match 'twiml/goodbye' => 'twiml#goodbye'
  match 'twiml/phone_call' => 'twiml#phone_call'
  match 'twiml/client_call' => 'twiml#client_call'
  match 'twiml/ivr' => 'twiml#ivr'
  match 'twiml/enqueue_caller' => 'twiml#enqueue_caller'
  match 'twiml/wait_url' => 'twiml#wait_url'
  match 'twiml/save_recording' => 'twiml#save_recording'
  match 'twiml/send_sms' => 'twiml#send_sms'
  match 'twiml/modal_sms' => 'twiml#modal_sms'

  match 'dashboard' => 'home#dashboard'
  root :to => 'home#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Disaster Remote Response" %></title>
    <%= csrf_meta_tags %>
    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
  <body>

    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="/">Disaster Remote Response</a>
          <div class="container nav-collapse">
            <ul class="nav pull-right">
              <% unless user_signed_in?%>
                <li class="divider"></li>
                <li><%= link_to "Log in", "#login_modal", :id => 'loginModal', "data-toggle" => "modal"%>
                <li><%= link_to "Sign up", "#signup_modal", :id => 'signupModal', "data-toggle" => "modal"%>              
              <% else %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                  <%=current_user.email%>
                  <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete%></li>
                </ul>
       
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->

        </div>
      </div>
    </div>

    <div class="container push_container">
        <div class="row">
          <div class="span12">
            <% if notice %>
            <p class="notice"><%= notice %></p>
            <% end %>
            <% if alert %>
            <p class="alert"><%= alert %></p>
            <% end %>
             <%= yield %>
          </div>
        </div><!--/row-->

      <footer>
        <p>&copy; Disaster Remote Response 2012</p>
        <!-- <div class="follow-buttons"> -->
          <!-- <div style="vertical-align:middle; margin-right:20px"> -->
            <a href="https://twitter.com/maggit" class="twitter-follow-button" data-show-count="false">Follow @maggit</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          <!-- </div> -->
          <!-- <div style="vertical-align:bottom"> -->
            <a href="https://twitter.com/harisamin" class="twitter-follow-button" data-show-count="false">Follow @harisamin</a>
            <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0];if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src="//platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
          <!-- </div> -->
        <!-- </div> -->
      </footer>

    </div> <!-- /container -->

  <% unless user_signed_in?%>  
    <!-- Login and sign up modal windows-->
  <div class="login-box modal hide fade" id="login_modal" tabindex="-1" role="dialog">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">×</button>
      <h3>Login to your account</h3>
    </div>
    <div class="modal-body">
      <%= form_for(resource, :as => resource_name, :url => session_path(resource_name), :class => "form-horizontal") do |f| %>
      <fieldset>
        <div class="input-prepend" title="Username">
          <span class="add-on">
            <i class="icon-envelope-alt"></i>
          </span>
          <input class="input-large" name="user[email]" id="email" type="text" placeholder="type email"/>
        </div>
        <div class="clearfix"></div>
        <div class="input-prepend" title="Password">
          <span class="add-on"><i class="icon-lock"></i></span>
          <input class="input-large" name="user[password]" id="password" type="password" placeholder="type password"/>
        </div>
        <div class="clearfix"></div>
        <label class="remember" for="remember"><input type="checkbox" id="remember" name="user[remember_me]"/>Remember me</label>
        <div class="btn-group button-login">  
          <button type="submit" class="btn btn-primary"><i class="icon-off icon-white"></i></button>
          <button type="submit" class="btn btn-primary">Login</button>
        </div>
        <div class="clearfix"></div>  
      <% end %>
      <h3>Forgot Password?</h3>
      <p>
          No problem, <%= link_to "click here", new_password_path(resource_name) %> to get a new password.
      </p>  
    </div>
  </div>

  <div class="login-box modal hide fade" id="signup_modal" tabindex="-1" role="dialog">
    <div class="modal-header">
      <button class="close" data-dismiss="modal">×</button>
      <h3>Create an account</h3>
    </div>
    <div class="modal-body">
      <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name), :class => "form-horizontal") do |f| %>
      <fieldset>
        <div class="input-prepend" title="Username">
          <span class="add-on">
            <i class="icon-envelope-alt"></i>
          </span>
          <input class="input-large" name="user[email]" id="email" type="text" placeholder="type email"/>
        </div>
        <div class="clearfix"></div>
        <div class="input-prepend" title="Password">
          <span class="add-on"><i class="icon-lock"></i></span>
          <input class="input-large" name="user[password]" id="password" type="password" placeholder="type password"/>
        </div>
        <div class="input-prepend" title="Password_confirmation">
          <span class="add-on"><i class="icon-lock"></i></span>
          <input class="input-large" name="user[password_confirmation]" id="password" type="password" placeholder="type password confirmation"/>
        </div>
        <div class="input-prepend" title="Phone_number">
          <span class="add-on">
            <i class="icon-phone"></i>
          </span>
          <input class="input-large" name="user[phone_number]" id="phone_number" type="text" placeholder="type phone number"/>
        </div>
        <div class="clearfix"></div>
        <div class="btn-group button-login">  
          <button type="submit" class="btn btn-primary"><i class="icon-off icon-white"></i></button>
          <button type="submit" class="btn btn-primary">Sign in</button>
        </div>
        <div class="clearfix"></div>  
      <% end %>
      <hr>
    </div>
  </div>
  <% end %>
    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->

    <script type="text/javascript" src="//static.twilio.com/libs/twiliojs/1.0/twilio.min.js"></script>
    <script src="http://js.pusher.com/1.12/pusher.min.js"></script>

    <%= javascript_include_tag "application" %>


  </body>
</html>